"""Generate docs/source_manifest.md from the real download manifest and run metadata.

Nothing in the manifest is typed by hand: file names, sizes, SHA-256 hashes, row
counts and the retrieval date all come from ``data/raw/_download_manifest.json``
written by ``scripts/download_data.py``, and the parsed row counts come from the
DuckDB database.

Usage
-----
    python scripts/build_source_manifest.py
"""

from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from src import config, pipeline  # noqa: E402

LICENCE_NOTE = """\
The City of San Diego publishes this dataset through its Open Data Portal under the
City's open data policy, which permits reuse. The City requests attribution and
states that it makes no warranty as to the accuracy, reliability or completeness of
the data. This project attributes the City as the source throughout and makes no
claim of endorsement."""


def parsed_row_counts() -> dict[str, int]:
    """Logical row counts as parsed by the pipeline, per extract."""
    if not config.DUCKDB_PATH.exists():
        return {}
    con = pipeline.connect(read_only=True)
    try:
        rows = con.execute(
            "SELECT source_extract, COUNT(*) FROM stg_union GROUP BY 1").fetchall()
        return {r[0]: r[1] for r in rows}
    except Exception:  # pragma: no cover - database built but base tables absent
        return {}
    finally:
        con.close()


def main() -> int:
    if not config.DOWNLOAD_MANIFEST.exists():
        print("data/raw/_download_manifest.json not found. Run: make download",
              file=sys.stderr)
        return 1

    manifest = json.loads(config.DOWNLOAD_MANIFEST.read_text())
    parsed = parsed_row_counts()
    run_meta = (json.loads(config.RUN_METADATA.read_text())
                if config.RUN_METADATA.exists() else {})

    key_by_filename = {meta["filename"]: key
                       for key, meta in config.SOURCE_EXTRACTS.items()}

    lines: list[str] = []
    a = lines.append

    a("# Source Manifest")
    a("")
    a("Exactly which files this analysis used, where they came from, and how to")
    a("verify you have the same ones. Generated by")
    a("[`scripts/build_source_manifest.py`](../scripts/build_source_manifest.py) — no")
    a("value here is typed by hand.")
    a("")
    a("| | |")
    a("|---|---|")
    a(f"| Publisher | {manifest['publisher']} |")
    a(f"| Dataset | Reports of non-emergency problems submitted by users of Get It Done |")
    a(f"| Dataset page | <{manifest['dataset_page']}> |")
    a(f"| Retrieved | {manifest['generated_at_utc']} |")
    if run_meta:
        a(f"| Data snapshot date | **{run_meta['snapshot_date']}** "
          f"(derived from the data — see below) |")
        a(f"| Records after processing | {run_meta['fact_rows']:,} |")
    a(f"| Update frequency | Daily, by the City |")
    a("")
    a("---")
    a("")
    a("## Files used")
    a("")
    a("| Role | File | Size | Rows parsed | Retrieved | Published (server) |")
    a("|---|---|---:|---:|---|---|")
    for entry in manifest["files"]:
        if "error" in entry:
            a(f"| FAILED | `{entry['filename']}` | — | — | — | {entry['error']} |")
            continue
        key = key_by_filename.get(entry["filename"])
        rows = parsed.get(key)
        rows_text = f"{rows:,}" if rows is not None else "n/a"
        size_mb = entry["size_bytes"] / 1e6
        a(f"| {entry['role']} | `{entry['filename']}` | {size_mb:,.1f} MB | "
          f"{rows_text} | {entry['retrieved_at_utc'][:10]} | "
          f"{entry.get('last_modified_header', 'n/a')} |")
    a("")
    a("## Integrity")
    a("")
    a("SHA-256 of each file as downloaded. The City refreshes these files daily, so a")
    a("later download will legitimately produce different hashes — these identify the")
    a("exact snapshot this analysis was run against.")
    a("")
    a("| File | SHA-256 | Physical lines |")
    a("|---|---|---:|")
    for entry in manifest["files"]:
        if "error" in entry:
            continue
        a(f"| `{entry['filename']}` | `{entry['sha256']}` | "
          f"{entry['physical_data_lines']:,} |")
    a("")
    a("Verify locally with:")
    a("")
    a("```bash")
    a("shasum -a 256 data/raw/*.csv        # macOS")
    a("sha256sum data/raw/*.csv            # Linux")
    a("```")
    a("")
    a("**Physical lines vs rows parsed.** The physical count is newline-delimited lines")
    a("minus the header. Get It Done free-text fields can contain embedded newlines, so")
    a("the two differ; the parsed count from DuckDB is authoritative.")
    a("")
    a("## Source URLs")
    a("")
    a("All files come from the City's own object store. No third-party mirror was used.")
    a("")
    for entry in manifest["files"]:
        a(f"- `{entry['filename']}`")
        a(f"  <{entry['url']}>")
    a("")
    a("## Scope decision")
    a("")
    a("The dataset also offers closed-year files for 2016–2024 and per-district files.")
    a("They were **excluded**. Two reasons:")
    a("")
    a("1. None of the twelve business questions needs history before 2025.")
    a("2. The chosen scope has a property the analysis depends on — a request submitted")
    a("   on or after 2025-01-01 must be either still open, closed in 2025, or closed in")
    a("   2026, so **every submission month from January 2025 is completely covered**.")
    a("   That is what makes the year-over-year demand comparison defensible. Adding")
    a("   partial older years would not extend that guarantee.")
    a("")
    a("`scripts/download_data.py --all-closed` retrieves the full set if needed.")
    a("")
    a("## Snapshot date")
    a("")
    if run_meta:
        a(f"**{run_meta['snapshot_date']}**, derived from the data rather than assumed.")
        a("")
        a("For active records the published `case_age_days` equals *(extract date − request")
        a("date)*, so the extract date is recoverable as the modal value of")
        a(f"`date_requested + case_age_days`. It agrees for")
        a(f"**{run_meta['snapshot_support_pct']}%** of active records")
        a(f"({run_meta['snapshot_support_records']:,} of them). See audit check DQ-03.")
    else:
        a("PENDING — pipeline has not been run.")
    a("")
    a("## Fields excluded from every output")
    a("")
    a("Although the source is public, these fields are dropped before anything is")
    a("written to disk. See [`07_methodology/methodology.md`](../07_methodology/methodology.md) §9.")
    a("")
    a("| Field | Reason |")
    a("|---|---|")
    a("| `public_description` | Resident-submitted free text |")
    a("| `street_address` | Exact point address |")
    a("| `lat`, `lng` | Exact coordinates; geography is published at district / community / ZIP |")
    a("| `referred` (raw text) | Contains staff and vendor email addresses; normalized to a destination label |")
    a("| `iamfloc`, `floc` | Internal asset identifiers, no analytical value here |")
    a("| `sap_notification_number` | Internal system identifier |")
    a("")
    a("## Licensing and attribution")
    a("")
    a(LICENCE_NOTE)
    a("")
    a("## Caveats carried from the source")
    a("")
    a("The City states, and this project repeats wherever a conclusion is drawn:")
    a("")
    a("> This data includes every user-submitted report and should not be considered an")
    a("> official record of City maintenance work. This data does not include details")
    a("> about any work performed to fix a problem or the date and time work was completed.")
    a("")
    a("Additional conditions found by this project's own audit — dual semantics in")
    a("`case_age_days`, an unstable service taxonomy, cross-file duplicate ids — are")
    a("quantified in [`02_data_audit/data_quality_report.md`](../02_data_audit/data_quality_report.md).")
    a("")
    a("---")
    a("")
    a(f"*Generated {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}.*")

    config.DOCS_DIR.mkdir(parents=True, exist_ok=True)
    out = config.DOCS_DIR / "source_manifest.md"
    out.write_text("\n".join(lines) + "\n")
    print(f"  [out] {out.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
